name: Build and Deploy
on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: vuepress-deploy
      uses: jenkey2011/vuepress-deploy@master
      env:
        ACCESS_TOKEN: ${{ secrets.BRAND_VUEPRESS_DEPLOY_ACCESS_TOKEN }}
        TARGET_REPO: royaleapi/brand
        TARGET_BRANCH: gh-pages
        BUILD_SCRIPT: npm ci && npm run docs:build
        BUILD_DIR: docs/.vuepress/dist/
        CNAME: brand.royaleapi.com